"use client";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { BookmarksProvider } from "./(contexts)/BookmarksContext";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentPath =
    typeof window !== "undefined" ? window.location.pathname : "";
  console.log(currentPath);
  return (
    <BookmarksProvider>
      <html lang="en">
        <body className={`${outfit.variable}`}>
          <Header />
          {children}
        </body>
      </html>
    </BookmarksProvider>
  );
}
